version: 0.2

phases:
  install:
    # Specify runtime version if needed
    runtime-versions:
      nodejs: 18 # Or your required Node.js version
    commands:
      # --- START: Commands to enter GitHub zip subdirectory ---
      - echo "Initial working directory:"
      - pwd
      - echo "Listing root directory contents:"
      - ls -lA
      # Find the top-level directory created by GitHub zipball (assumes only one non-hidden)
      - export SOURCE_DIR=$(ls -A | grep -v '^\.' | head -n 1) # Find first non-hidden entry
      - echo "Detected source directory:$SOURCE_DIR"
      # Use YAML block scalar '|' for multi-line shell command correctness
      - |
        if [ -z "$SOURCE_DIR" ] || [ ! -d "$SOURCE_DIR" ]; then 
          echo "ERROR: Could not find source subdirectory from zipball"
          ls -A
          exit 1
        fi
      # Change into the source directory
      - cd "$SOURCE_DIR"
      - echo "Changed directory to $SOURCE_DIR. New working directory:"
      - pwd
      - echo "Contents of source directory '$SOURCE_DIR':"
      - ls -lA
      # --- END: Added commands ---

      # --- Install dependencies (now inside the correct directory) ---
      - echo "Installing application dependencies..."
      - npm install

      # --- Install Security Scan Tools Here (if needed) ---
      # Examples...
      # - npm install -g snyk
      # - pip install trufflehog
      # - curl --create-dirs -sSLo sonar.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-latest-linux.zip && unzip sonar.zip && export PATH=$PATH:./sonar-scanner-*/bin

  pre_build:
    commands:
      # --- Run Security Scans Here ---
      - echo "Running security scans..."
      # Examples...
      # - snyk test --fail-on=high --all-projects || true
      # - snyk code test --fail-on=high --all-projects || true
      # - trufflehog git file://. --fail
      # - sonar-scanner

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Running build commands (e.g., compilation, tests)..."
      # Add your application build commands here (if any)
      # Example: npm test
      # Example: npm run build

  post_build:
    commands:
        - echo "Build completed on `date`"
        # Commands to prepare artifacts for deployment
        # Example: Create zip for Elastic Beanstalk (if needed)
        # - echo "Creating deployment artifact..."
        # - zip -r ../deployment_package.zip . -x ".git/*" "node_modules/*" # From current (subdir) path

artifacts:
  # Define files relative to the current working directory (the SOURCE_DIR)
  # to be included in the CodeBuild output artifact
  files:
    # Include all files needed for deployment from the subdirectory
    - '**/*'
    #1. Include core application files
    - 'package.json'
    - 'app.js'
    # 2. Include all installed Node dependencies
    - 'node_modules/**/*'
    # 3. Include the configuration folder
    - '.ebextensions/**/*'
  # The base-directory is effectively the $SOURCE_DIR now due to the 'cd' command
  base-directory: '.' # Optional, '.' is default relative to current dir

# cache: # Optional: Define paths to cache relative to $SOURCE_DIR
#   paths:
#     - 'node_modules/**/*'
